PACKAGE_TARNAME = papi
prefix = /home/s200010035/papi/src/install
exec_prefix = ${prefix}
datarootdir = ${prefix}/share
datadir = ${datarootdir}/${PACKAGE_TARNAME}
DATADIR = $(DESTDIR)$(datadir)
INCLUDE = -I. -I${prefix}/include
CC	= gcc
F77	= gfortran
CC_R	= $(CC) -pthread
CFLAGS	=  -g -Wextra  -Wall -DPAPI_NUM_COMP=3 -O1

